on:
  push:
    branches: [master]

name: deploy

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      
      - name: Run deploy script
        run: Rscript deploy.R
